name: Build and Push Docker Image

on:

  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      run: echo "rn3B6fAAYX.!xZV" | docker login -u "alegnta" --password-stdin

    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: alegnta/gcrs-backended:latest

  deploy:
      needs: build-and-push
      runs-on: ubuntu-latest
  
      steps:
      - name: Checkout code
        uses: actions/checkout@v3
  
      - name: Set up SSH agent
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.EC2_KEY }}
  
      - name: Pull Docker image and deploy on aws EC2
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
            sudo docker login -u "${{ secrets.DOCKER_USERNAME }}" -p "${{ secrets.DOCKER_PASSWORD }}"
            sudo docker stop gcrs-backeend || true
            sudo docker rm gcrs-backeend || true
            sudo docker rmi alegnta/gcrs-backended:latest
            sudo docker pull alegnta/gcrs-backended:latest
            sudo docker run -d --name gcrs-backeend -p 3000:6000 alegnta/gcrs-backended:latest
          EOF